# Generated by Django 6.0.4 on 2026-05-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('accountant', 'Accountant'), ('inventory', 'Inventory Manager')], default='admin', max_length=20),
        ),
    ]
