# Generated by Django 6.0.4 on 2026-05-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='performance_tag',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
    ]
