# Generated by Django 6.0.4 on 2026-05-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0004_employee_performance_tag_employee_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
