import React from 'react';
import { Lightbulb, ArrowRight, Zap, TrendingUp, Users } from 'lucide-react';

const recommendations = [
  {
    id: 1,
    title: 'Optimize Supply Chain Logistics',
    category: 'Operations',
    icon: Zap,
    impact: 'High',
    description: 'AI models suggest rerouting shipments from the West Coast hub to the Midwest facility to reduce average delivery time by 1.2 days and cut transport costs by 8%.',
    actionText: 'Review Routing Plan'
  },
  {
    id: 2,
    title: 'Price Adjustment for Q4',
    category: 'Revenue',
    icon: TrendingUp,
    impact: 'Medium',
    description: 'Based on competitor analysis and historical demand, slightly increasing the price of "Premium Service Tier" by 5% is predicted to have minimal impact on churn while boosting quarterly revenue by $45,000.',
    actionText: 'View Pricing Model'
  },
  {
    id: 3,
    title: 'Targeted Retention Campaign',
    category: 'Customer Success',
    icon: Users,
    impact: 'High',
    description: 'We identified 124 enterprise accounts showing early signs of churn (decreased usage). Recommend initiating a targeted outreach campaign offering a free strategy session.',
    actionText: 'Generate Campaign List'
  }
];

const Recommendations = () => {
  return (
    <div>
      <div className="page-header" style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
        <div style={{ padding: '0.75rem', backgroundColor: 'var(--warning-bg)', color: 'var(--warning)', borderRadius: 'var(--radius-md)' }}>
          <Lightbulb size={32} />
        </div>
        <div>
          <h1 className="page-title">AI Recommendations</h1>
          <p className="page-subtitle">Actionable insights generated by analyzing your business data.</p>
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
        {recommendations.map(rec => {
          const Icon = rec.icon;
          return (
            <div key={rec.id} className="card" style={{ 
              display: 'flex', 
              gap: '1.5rem', 
              alignItems: 'flex-start',
              position: 'relative',
              overflow: 'hidden'
            }}>
              <div style={{ 
                position: 'absolute', 
                top: 0, 
                left: 0, 
                width: '4px', 
                height: '100%', 
                backgroundColor: rec.impact === 'High' ? 'var(--primary)' : 'var(--warning)' 
              }}></div>
              
              <div style={{ 
                padding: '1rem', 
                backgroundColor: 'var(--bg-color)', 
                borderRadius: '50%',
                color: 'var(--text-main)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center'
              }}>
                <Icon size={24} />
              </div>

              <div style={{ flex: 1 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.75rem' }}>
                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.25rem' }}>
                      <h3 style={{ fontSize: '1.25rem', fontWeight: '600' }}>{rec.title}</h3>
                      <span className="badge" style={{ backgroundColor: 'var(--border-color)', color: 'var(--text-main)' }}>
                        {rec.category}
                      </span>
                    </div>
                    <div style={{ fontSize: '0.875rem', color: 'var(--text-muted)' }}>
                      Estimated Impact: <strong style={{ color: rec.impact === 'High' ? 'var(--primary)' : 'inherit' }}>{rec.impact}</strong>
                    </div>
                  </div>
                </div>
                
                <p style={{ color: 'var(--text-main)', lineHeight: '1.6', marginBottom: '1.25rem' }}>
                  {rec.description}
                </p>

                <button className="btn btn-primary" style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem' }}>
                  {rec.actionText} <ArrowRight size={16} />
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default Recommendations;
