# Generated by Django 6.0.4 on 2026-05-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_flagged',
            new_name='is_fraud',
        ),
    ]
